camera_common:
  image_width: 640
  image_height: 360
  intrinsics_matrix:  [343.50, 0.0, 320.0, 
                        0.0, 343.50, 180.0, 
                        0.0, 0.0, 1.0]
  baseline: 0.8
  fov: 1.5
  format: "R8G8B8"
  clip_near: 0.1
  clip_far: 200.0

camera1:
  world_coordinates:
    x: 0.0
    y: -2.9
    z: 3.0
    roll: 0.0
    pitch: 0.50
    yaw: 1.57

camera2:
  world_coordinates:
    x: 0.0
    y: 6.6
    z: 3.0
    roll: 0.0
    pitch: 0.50
    yaw: -1.57